del /f logs\statistics.csv
call demo.cmd andrew0928
call demo.cmd andy19900208
call demo.cmd julian-chu
call demo.cmd jwchen-dev
call demo.cmd toyo0103
call demo.cmd acetaxxxx
call demo.cmd demo
call demo.cmd borischin
call demo.cmd levichen